version: "2"

services:
  uwsgi-buster:
    build: ./uwsgi-gevent-buster
    image: uwsgi-gevent:buster
    privileged: true
    restart: always
    volumes:
      - ./src:/root
    ports:
      - 10080:80
    environment:
      - LOG_LEVEL=DEBUG
      - PROCESSES=2
      - THREADS=10
      - GEVENT=1
      - GEVENT_NUMS=100
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - ENV=DEV
      - DYNAMODB_TABLE=test_table
      - REGION=ap-northeast-1
    entrypoint:
      - sh
      - -c
      - "/root/entrypoint.sh"
    ulimits:
      nofile:
        soft: 98304
        hard: 98304