version: "2"

services:
  uwsgi-alpine:
    build: ./uwsgi-gevent-alpine
    image: uwsgi-gevent:alpine
    privileged: true
    restart: always
    volumes:
      - ./src:/root
    ports:
      - 10080:80
    environment:
      - LOG_LEVEL=DEBUG
      - PROCESSES=2
      - GEVENT=1
      - GEVENT_NUMS=100
    entrypoint:
      - sh
      - -c
      - "/root/entrypoint.sh"

  uwsgi-slim:
    build: ./uwsgi-gevent-slim
    image: uwsgi-gevent:slim
    privileged: true
    restart: always
    volumes:
      - ./src:/root
    ports:
      - 10081:80
    environment:
      - LOG_LEVEL=DEBUG
      - PROCESSES=2
      - GEVENT=1
      - GEVENT_NUMS=100
    entrypoint:
      - sh
      - -c
      - "/root/entrypoint.sh"

  uwsgi-buster:
    build: ./uwsgi-gevent-buster
    image: uwsgi-gevent:buster
    privileged: true
    restart: always
    volumes:
      - ./src:/root
    ports:
      - 10082:80
    environment:
      - LOG_LEVEL=DEBUG
      - PROCESSES=2
      - THREADS=10
      - GEVENT=0
      - GEVENT_NUMS=100
    entrypoint:
      - sh
      - -c
      - "/root/entrypoint.sh"
